build: false

environment:
  matrix:
    - nodejs_version: "0.10"
    - nodejs_version: "0.8"
    - nodejs_version: "0.11"

install:
  - npm update -g npm
  - npm install

test_script:
  - node --version
  - npm --version
  - npm test
